### ISSUE TITLE
Tox builder seems to be expecting a tox file

### ISSUE THREAD

**Issue by orviz** [indigo-dc/jenkins-pipeline-library#143] opened 2021-04-16 10:29 UTC
Even though the command `tox` itself does not require a configuration file to be provided, JePL is currently requesting that. The error `eu.indigo.compose.DockerCompose.escapeWhitespace(DockerCompose.groovy:117)` is obtained when no `tox_file` is provided (see [sample failure](https://jenkins.eosc-synergy.eu/job/eosc-synergy-org/job/DEEPaaS/job/eosc-synergy/8/console))

**Comment by samuelbernardolip** [comment] 2021-05-20 22:00
https://github.com/EOSC-synergy/DEEPaaS/blob/6398cb85d07a20b3df04c7b9826a1e05e906050e/.sqa/config.yml#L6L8

This is wrong and not expected... Tox configuration or any other build tool configuration only appears in the stage where it will run.

**Comment by samuelbernardolip** [comment] 2021-05-20 22:05
https://github.com/EOSC-synergy/DEEPaaS/blob/6398cb85d07a20b3df04c7b9826a1e05e906050e/.sqa/config.yml#L7

@orviz  tox.ini file when set should be the full path to the expected location inside container. In PR I was setting the full project path but that is wrong, because the tox will run inside container, so depends on the user configuration for the container itself. So always require the user or the auto-configuration system to set it as expected.

**Comment by samuelbernardolip** [comment] 2021-05-20 22:10
Closing this issue, since is not a bug from JePL side.

**Closed by samuelbernardolip** 2021-05-20 22:10 UTC
Labels: bug
