### ISSUE TITLE
Different behaviours (different target directories) when repos are checked-out 

### ISSUE THREAD

**Issue by orviz** [indigo-dc/jenkins-pipeline-library#108] opened 2020-10-27 18:01 UTC
Say we have `/jepl` folder as the volume's target in docker-compose.yml:
- If we use `config: project_repos` to checkout a _foo_ repo, its content will be stored under __/jepl/foo__
- If we don't define the repo in config.yml (so by default the branch from _foo_ repo that triggered the build is downloaded), the content is however placed under __/jepl/__

We should homogeneize this behaviour so that in both cases, the repo is placed in the same path.

**Comment by samuelbernardolip** [comment] 2020-12-04 00:46
As I understand from the description of this issue, this doesn't seems to be a bug, but an expected behaviour.
Taking as example the work produced in Worsica TS, the docker-compose.yml should reflect the content planed for the workspace and not the opposite. This is important so we can keep a logical definition for the reference source.
Going deeper to the details, when using the triggered branch from github or other git management system, they will pass the variables with independent definitions not following a standard. So when gitSCM pick that metadata it will produce the workspace by default using the provided properties.
That's why this kind of details can only be standardized in an above level with a template approach, as we can do using SQAaaS API or Web.
So I answer to this issue as wontfix.

**Closed by samuelbernardolip** 2020-12-04 00:46 UTC
Labels: bug
